apiVersion: maistra.io/v2
kind: ServiceMeshControlPlane
metadata:
  name: basic
  namespace: istio-system
spec:
  security:
    controlPlane:
      mtls: true
    dataPlane:
      automtls: true
      mtls: true
    identity:
      type: Kubernetes
  tracing:
    type: Jaeger
    sampling: 10000
  gateways:
    openshiftRoute:
      enabled: false
    enabled: false
    additionalEgress:
      egw01-vs1:
        enabled: true
        namespace: vs1
        runtime:
          container:
            resources:
              limits:
                cpu: 500m
                memory: 512Mi
              requests:
                cpu: 100m
                memory: 128Mi
          deployment:
            autoScaling:
              enabled: true
            replicas: 3
    additionalIngress:
      igw01-vs1:
        enabled: true
        namespace: vs1
        runtime:
          container:
            resources:
              limits:
                cpu: 500m
                memory: 512Mi
              requests:
                cpu: 100m
                memory: 128Mi
          deployment:
            autoScaling:
              enabled: false
              replicas: 3
        service:
          type: ClusterIP     
  policy:
    type: Istiod
  addons:
    grafana:
      enabled: true
    jaeger:
      install:
        storage:
          type: Memory
    kiali:
      enabled: true
    prometheus:
      enabled: true
  telemetry:
    type: Istiod
  version: v2.2

